### ISSUE TITLE
Add theme for academic paper, journal, and thesis

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/themes#1]
https://github.com/yamasy1549/nitac_tex_template

author: @yamasy1549

## Theme name candidates

- vivliostyle/theme-academic
- vivliostyle/theme-thesis
- vivliostyle/theme-journal
- vivliostyle/theme-{more fancy name}

## Merging process

1. Create a PR
2. Maintainers will review the PR
3. Merge into the repo & publish on npm

**Comment by yamasy1549** [comment]
academicは作ったのでclose
