### ISSUE TITLE
日本語のセクション番号参照が「1.1.1章」の形式なのは不自然

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/themes#127]
Vivliostyle Base Theme で、日本語のセクション番号参照が「1.1.1章」の形式になるように設定されています。

https://github.com/vivliostyle/themes/blob/ebf926f25ccec72fc01bf7f27cad6dcac4af9273/packages/%40vivliostyle/theme-base/css/partial/section.css#L24-L32

日本語以外で "§1.1.1" の形式になっているのが、日本語では "1.1.1章" というのは不自然だと思います。日本語の「章」というのは普通はトップレベルの番号に対してだけ使われます。下位のセクションの番号を合わせた番号に対して「章」を付けるのは不自然です。この日本語用の設定は削除して、日本語であっても "§1.1.1" の形式にするほうがよいと思います。

**Comment by spring-raining** [comment]
そうですね、「1.1.1章」という表記はたしかに不自然です。理想的には「1章」「1.1節」
