### ISSUE TITLE
vivliostyle-theme-scripts と create-vivliostyle-theme のリリース権限について

### ISSUE THREAD

**Issue by yamasy1549** [vivliostyle/themes#14]
@uetchy 
npm パッケージ vivliostyle-theme-scripts と create-vivliostyle-theme をリリースしようとしたら、パーミッションが必要と言われました。これらを vivliostyle の npm organization で管理するか、あるいは collaborator に加えていただけますか？ （どちらがいいんでしょう……🤔 ）

https://www.npmjs.com/package/vivliostyle-theme-scripts
https://www.npmjs.com/package/create-vivliostyle-theme

**Comment by uetchy** [comment]
@yamasy1549 collaboratorに追加するのでnpmユーザー名を教えてください

**Comment by yamasy1549** [comment]
@uetchy yamasy1549 です、よろしくお願いします
