### ISSUE TITLE
Themeの開発ガイドラインをつくる

### ISSUE THREAD

**Issue by yamasy1549** [vivliostyle/themes#69]
- CSSの書き方など

**Comment by ogwata** [comment]
- [Tools](https://github.com/vivliostyle/themes#tools)を使ったThemeの作成方法
- テンプレートとその使い方の説明

**Comment by ogwata** [comment]
#68 との切り分けはどうするのでしょう？　どちらかに統一した方がよいと思います。

**Comment by akabekobeko** [comment]
#68 を close してこちらに集約がよいと思います

**Comment by ogwata** [comment]
2日会議で、yamasy1549さんから以下のような提案がありました。

> この辺に追記ですかね > Themeのガイドライン
> https://github.com/vivliostyle/themes/blob/master/DESIGN.md

そうですね、DESIGN.mdを叩き台とするのでよいと思います。
翻訳＋追記＋わかりやすく説明という感じでしょうか。
