### ISSUE TITLE
Theme の運用ガイドラインを作成する

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/themes#71]
refs #69

Theme を開発した後の実運用に関わるガイドラインを作成する。#69 はエンド ユーザー向けでこちらは Vivliostyle 運営も含みます。

ざっと思いついたものを列挙してみます。

- 名付け方
  - 基本的に自由
  - A4 や縦書きなど CSS や Viviliostyle Viewer、Pub から動的変更しそうなものは含めない
  - 目的の明確なものと抽象的なもので分かれるだろう
  - 実社会や専門分野で規格の定められているものなら、それを踏襲するのがよい
  - などなど
- 対象単位
  - 基本は文書、帳票、帳簿
  - 版型や段組みの単位で小さなテーマを作成して組み合わせる案もあったが、これらはサンプルとして CSS のスニペットを公開すれば十分ではないか？
- 公式テーマ採用
  - 申請と審査
  - どこに申請して誰が審査するか？
- 参考資料
  - 既存のテーマをサポートしているソフトウェアのガイドラインを見つけたら随時、追加予定 
  - [テーマレビュー - WordPress Codex 日本語版](https://wpdocs.osdn.jp/%E3%83%86%E3%83%BC%E3%83%9E%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC)

**Comment by ogwata** [comment]
- [Tools](https://github.com/vivliostyle/themes#tools)を使ったThemeの作成方法
- テンプレートの公開とその使い方説明

**Comment by akabekobeko** [comment]
@ogwata それは #69 の方になると思います

**Comment by akabekobeko** [comment]
ガイドの中に #69の開発系と本 issue のような運用系の大別がある感じです
